config/routes.rb
Rails.application.routes.draw do 
  

  root 'puzzleskeletons#index'
  resources :puzzleskeletons do
    resources :puzzlepieces
  end 
  get 'welcome/index'

end

app/models/puzzle1.rb
class Puzzle1 < ActiveRecord::Base
end

app/models/puzzlepiece.rb
class Puzzlepiece < ActiveRecord::Base
end

app/models/puzzleskeleton.rb
class Puzzleskeleton < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puzzlepieces_controller.rb
class PuzzlepiecesController < ApplicationController
  before_action :set_puzzleskeleton, only: [:create, :new, :index]
  before_action :set_puzzlepiece, only: [:show, :edit, :update, :destroy]

  # GET /puzzlepieces
  # GET /puzzlepieces.json
  def index
    @puzzlepieces = @puzzleskeleton.puzzlepieces
  end

  # GET /puzzlepieces/1
  # GET /puzzlepieces/1.json
  def show
  end

  # GET /puzzlepieces/new
  def new
    @puzzlepiece = @puzzleskeleton.puzzlepieces.build
  end

  # GET /puzzlepieces/1/edit
  def edit
  end

  # POST /puzzlepieces
  # POST /puzzlepieces.json
  def create
    @puzzlepiece = @puzzleskeleton.puzzlepieces.build(puzzlepiece_params)

    respond_to do |format|
      if @puzzlepiece.save
        format.html { redirect_to @puzzleskeleton, notice: 'puzzlepiece was successfully created.' }
        format.json { render :show, status: :created, location: @puzzlepiece }
        format.js {redirect_via_turbolinks_to [@puzzlepiece.puzzleskeleton, @puzzlepiece]}
      else
        format.html { render :new }
        format.json { render json: @puzzlepiece.errors, status: :unprocessable_entity }
        format.js { render partial: 'shared/ajax_form_errors', locals: {model: @puzzlepiece}, status: 400}
      end
    end
  end

  # PATCH/PUT /puzzlepieces/1
  # PATCH/PUT /puzzlepieces/1.json
  def update
    respond_to do |format|
      if @puzzlepiece.update(puzzlepiece_params)
        format.html { redirect_to [@puzzleskeleton, @puzzlepiece], notice: 'puzzlepiece was successfully updated.' }
        format.json { render :show, status: :ok, location: @puzzlepiece }
        format.js {redirect_via_turbolinks_to [@puzzlepiece.puzzleskeleton, @puzzlepiece]}
      else
        format.html { render :edit }
        format.json { render json: @puzzlepiece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzlepieces/1
  # DELETE /puzzlepieces/1.json
  def destroy
    @puzzlepiece.destroy
    respond_to do |format|
      format.html { redirect_to puzzleskeleton_puzzlepieces_path(@puzzleskeleton), notice: 'puzzlepiece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_puzzleskeleton
      @puzzleskeleton = Puzzleskeleton.friendly.find(params[:puzzleskeleton_id])
    end

    def set_puzzlepiece
      @puzzlepiece = Puzzlepiece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puzzlepiece_params
      params.require(:puzzlepiece).permit(:number, :puzzlepiece_id)
    end
end

app/controllers/puzzleskeletons_controller.rb
class PuzzleskeletonsController < ApplicationController
  before_action :set_puzzleskeleton, only: [:show, :edit, :update, :destroy]

  # GET /puzzleskeletons
  # GET /puzzleskeletons.json
  def index
    @puzzleskeletons = Puzzleskeleton.all
  end

  # GET /puzzleskeletons/1
  # GET /puzzleskeletons/1.json
  def show
  end

  # GET /puzzleskeletons/new
  def new
    @puzzleskeleton = Puzzleskeleton.new
  end

  # GET /puzzleskeletons/1/edit
  def edit
  end

  # POST /puzzleskeletons
  # POST /puzzleskeletons.json
  def create
    @puzzleskeleton = Puzzleskeleton.new(puzzleskeleton_params)

    respond_to do |format|
      if @puzzleskeleton.save
        format.html { redirect_to @puzzleskeleton, notice: 'Puzzleskeleton was successfully created.' }
        format.json { render :show, status: :created, location: @puzzleskeleton }
      else
        format.html { render :new }
        format.json { render json: @puzzleskeleton.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puzzleskeletons/1
  # PATCH/PUT /puzzleskeletons/1.json
  def update
    respond_to do |format|
      if @puzzleskeleton.update(puzzleskeleton_params)
        format.html { redirect_to @puzzleskeleton, notice: 'Puzzleskeleton was successfully updated.' }
        format.json { render :show, status: :ok, location: @puzzleskeleton }
      else
        format.html { render :edit }
        format.json { render json: @puzzleskeleton.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzleskeletons/1
  # DELETE /puzzleskeletons/1.json
  def destroy
    @puzzleskeleton.destroy
    respond_to do |format|
      format.html { redirect_to puzzleskeletons_url, notice: 'Puzzleskeleton was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puzzleskeleton
      @puzzleskeleton = Puzzleskeleton.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puzzleskeleton_params
      params.require(:puzzleskeleton).permit(:name, :puzzleskeleton_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/piece_helper.rb
module PieceHelper
end

app/helpers/puzzle1s_helper.rb
module Puzzle1sHelper
end

app/helpers/puzzleskeletons_helper.rb
module PuzzleskeletonsHelper
end

app/helpers/scaffold_helper.rb
module ScaffoldHelper
end

app/helpers/spuzzles_helper.rb
module SpuzzlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puzzle</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puzzlepieces/_form.html.erb
<%= form_for(@puzzlepiece) do |f| %>
  <% if @puzzlepiece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puzzlepiece.errors.count, "error") %> prohibited this puzzlepiece from being saved:</h2>

      <ul>
      <% @puzzlepiece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puzzlepieces/_puzzlepiece.html.erb
<div id="puzzlepiece" class="ui-widget-content">
  	<p>This is a Piece of the Puzzle</p>
</div>

app/views/puzzlepieces/_puzzleskeleton.html.erb
<div id="snaptarget" class="ui-widget-header">
   Build the puzzle in here.
</div>

app/views/puzzlepieces/edit.html.erb
<h1>Editing Puzzlepieces</h1>

<%= render 'form' %>

<%= link_to 'Show', @puzzlepiece %> |
<%= link_to 'Back', puzzlepieces_path %>

app/views/puzzlepieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Puzzlepieces</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puzzlepiece.each do |puzzlepiece| %>
      <tr>
        <td><%= puzzlepiece.number %></td>
        <td><%= link_to 'Show', puzzlepiece %></td>
        <td><%= link_to 'Edit', edit_puzzlepiece_path(puzzlepiece) %></td>
        <td><%= link_to 'Destroy', puzzlepiece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>     
    <% end %>
  </tbody>
</table>

<% @puzzlepiece.each do |puzzlepiece| %>
  <div class="puzzlepiece" class="ui-widget-content">
    <p>This puzzle piece number <%= puzzlepiece.number %></p>
  </div>
<% end %>

<% @puzzlepiece.each do |puzzlepiece| %>
  <div id="snaptarget" class="ui-widget-content">
    <p>Build the puzzle in here.</p>
  </div>
<% end %>

<script>
  $(function() {
    $( ".puzzlepiece" ).draggable({ snap: true, snap: ".ui-widget-content", snapMode: "inner" }, { containment: "#box-border-layout", scroll: false });
  });
</script>

<br>

<%= link_to 'New puzzlepiece', new_puzzlepiece_path %>

app/views/puzzlepieces/new.html.erb
<h1>New Puzzlepiece</h1>

<%= render 'form' %>

<%= link_to 'Back', puzzlepieces_path %>

app/views/puzzlepieces/show.html.erb
<p id="notice"><%= notice %></p>

<div class="puzzlepiece" class="ui-widget-content">
  	<p>This puzzle piece number <%= @puzzlepiece.number %></p>
</div>

<%= link_to 'Edit', edit_puzzlepiece_path(@puzzlepiece) %> |
<%= link_to 'Back', puzzlepieces_path %>

app/views/puzzleskeletons/_form.html.erb
<%= form_for(@puzzleskeleton) do |f| %>
  <% if @puzzleskeleton.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puzzleskeleton.errors.count, "error") %> prohibited this puzzleskeleton from being saved:</h2>

      <ul>
      <% @puzzleskeleton.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puzzleskeletons/edit.html.erb
<h1>Editing Puzzleskeleton</h1>

<%= render 'form' %>

<%= link_to 'Show', @puzzleskeleton %> |
<%= link_to 'Back', puzzleskeletons_path %>

app/views/puzzleskeletons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Puzzleskeletons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puzzleskeletons.each do |puzzleskeleton| %>
      <tr>
        <td><%= puzzleskeleton.name %></td>
        <td><%= link_to 'Show', puzzleskeleton %></td>
        <td><%= link_to 'Edit', edit_puzzleskeleton_path(puzzleskeleton) %></td>
        <td><%= link_to 'Destroy', puzzleskeleton, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puzzleskeleton', new_puzzleskeleton_path %>

app/views/puzzleskeletons/new.html.erb
<h1>New Puzzleskeleton</h1>

<%= render 'form' %>

<%= link_to 'Back', puzzleskeletons_path %>

app/views/puzzleskeletons/show.html.erb
<p id="notice"><%= notice %></p>
<body>
 <center>

  <h1><%= @puzzleskeleton.name %></h1>
<div id="containment-wrapper">
  <div id="snaptarget" class="ui-widget-content">
   Build the puzzle in here.
  </div>
  <div id="snaptarget" class="ui-widget-content">
   Build the puzzle in here.
  </div>
  <div id="snaptarget" class="ui-widget-content">
   Build the puzzle in here.
  </div>
  <div id="snaptarget" class="ui-widget-content">
   	Build the puzzle in here.
  </div>


  <div id="puzzlepiece1" class="ui-widget-content">
  	<p>This is a Piece of the Puzzle</p>
  </div>
  <div id="puzzlepiece2" class="ui-widget-content">
  	<p>This is a Piece of the Puzzle</p>
  </div>
  <div id="puzzlepiece3" class="ui-widget-content">
  	<p>This is a Piece of the Puzzle</p>
  </div>
  <div id="puzzlepiece4" class="ui-widget-content">
  	<p>This is a Piece of the Puzzle</p>
  </div>
</div>

  <script>
  $(function() {
    $( "#puzzlepiece1" ).draggable({ snap: true, snap: ".ui-widget-content", snapMode: "inner" }, { containment: "#containment-wrapper", scroll: false });
  });
   $(function() {
    $( "#puzzlepiece2" ).draggable({ snap: true, snap: ".ui-widget-content", snapMode: "inner" }, { containment: "#containment-wrapper", scroll: false });
  });
  $(function() {
    $( "#puzzlepiece3" ).draggable({ snap: true, snap: ".ui-widget-content", snapMode: "inner" }, { containment: "#containment-wrapper", scroll: false });
  });
  $(function() {
    $( "#puzzlepiece4" ).draggable({ snap: true, snap: ".ui-widget-content", snapMode: "inner" }, { containment: "#containment-wrapper", scroll: false });
  });
  </script>



  <br>
  <div>
   <center>
    <%= link_to 'Back to all puzzleskeletons', root_path %>
  </div>
</body>

app/views/welcome/_background.html.erb
 <center>
  <div id="snaptarget" class="ui-widget-header">
    Build the puzzle in here.
  </div>
</center>

app/views/welcome/_puzzlepiece.html.erb
<div id="puzzlepiece" class="ui-widget-content">
  	<p>This is a Piece of the Puzzle</p>
</div>

<div id="puzzlepiece2" class="ui-widget-content">
  	<p>This is a Piece of the Puzzle</p>
</div>

app/views/welcome/index.html.erb
<h1><center>DRAGGABLE PUZZLE</center></h1>

<body>
  <script>
  $(function() {
    $( "#puzzlepiece" ).draggable({ snap: true, snap: ".ui-widget-header", snapMode: "inner-left" }, { containment: "#box-border-layout", scroll: false });
  	$( "#puzzlepiece2" ).draggable({ snap: true, snap: ".ui-widget-header", snapMode: "inner" }, { containment: "#box-border-layout", scroll: false });
  });
  </script>


  <%= render 'welcome/background' %>
  <%= render 'welcome/background' %>

  <%= render 'welcome/puzzlepiece' %>
</body>